const basePath = "/admin";
export const mainPathSlash = `/`;
export const dashboardPath = `${basePath}/dashboard`;
export const medicinesPath = `${basePath}/medicines`;
export const allMedicinesPath = `${basePath}/medicines/index`;
export const suppliersPath = `${basePath}/suppliers`;
export const purchasePath = `${basePath}/purchase`;
export const salesPath = `${basePath}/sales`;
export const reportsPath = `${basePath}/reports`;
